[package]
name = "hermes-cli"
version = "0.1.0"
edition = "2021"
description = "A command-line tool for complex email operations"
authors.workspace = true
license.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
